workflows:
  android-build:
    name: Tarifa Fácil Android
    max_build_duration: 60
    instance_type: linux_x2

    environment:
      flutter: stable

    scripts:
      - name: Instalar dependências
        script: |
          flutter pub get

      - name: Gerar APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
