import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:geolocator/geolocator.dart';
import 'package:http/http.dart' as http;
import 'package:intl/intl.dart';
import 'package:latlong2/latlong.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() => runApp(const TarifaFacilApp());

class AppConfig {
  double base, perKm, minFare, dynamic;
  AppConfig({this.base=3.0,this.perKm=2.5,this.minFare=7.0,this.dynamic=1.0});
  Map<String,dynamic> toJson()=>{'base':base,'perKm':perKm,'minFare':minFare,'dynamic':dynamic};
  static AppConfig from(Map<String,dynamic> j)=>AppConfig(base:(j['base']??3).toDouble(),perKm:(j['perKm']??2.5).toDouble(),minFare:(j['minFare']??7).toDouble(),dynamic:(j['dynamic']??1).toDouble());
}

class TarifaFacilApp extends StatefulWidget { const TarifaFacilApp({super.key}); @override State<TarifaFacilApp> createState()=>_AppState(); }
class _AppState extends State<TarifaFacilApp> {
  AppConfig config=AppConfig(); List<Map<String,dynamic>> history=[];
  @override void initState(){super.initState(); _load();}
  Future<void> _load() async { final p=await SharedPreferences.getInstance(); final c=p.getString('config'); final h=p.getString('history'); setState((){if(c!=null)config=AppConfig.from(jsonDecode(c)); if(h!=null)history=List<Map<String,dynamic>>.from(jsonDecode(h));}); }
  Future<void> saveConfig(AppConfig c) async {final p=await SharedPreferences.getInstance(); await p.setString('config',jsonEncode(c.toJson())); setState(()=>config=c);}
  Future<void> addHistory(double km,double fare) async {history.insert(0,{'date':DateTime.now().toIso8601String(),'km':km,'fare':fare}); if(history.length>30)history=history.sublist(0,30); final p=await SharedPreferences.getInstance(); await p.setString('history',jsonEncode(history)); setState((){});}
  @override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Tarifa Fácil',theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.green,brightness:Brightness.light),darkTheme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.green,brightness:Brightness.dark),home:Home(config:config,onSave:saveConfig,onHistory:addHistory,history:history));
}

class Home extends StatefulWidget { final AppConfig config; final Future<void> Function(AppConfig) onSave; final Future<void> Function(double,double) onHistory; final List<Map<String,dynamic>> history; const Home({super.key,required this.config,required this.onSave,required this.onHistory,required this.history}); @override State<Home> createState()=>_HomeState(); }
class _HomeState extends State<Home>{
  late AppConfig c; final map=MapController(); LatLng? origin,destination; List<LatLng> route=[]; double km=0; bool loading=false; int tab=0;
  @override void initState(){super.initState(); c=AppConfig(base:widget.config.base,perKm:widget.config.perKm,minFare:widget.config.minFare,dynamic:widget.config.dynamic);}
  double get fare=>((c.base+km*c.perKm)*c.dynamic).clamp(c.minFare,double.infinity);
  Future<void> current(){return Geolocator.requestPermission().then((p) async {if(p==LocationPermission.denied||p==LocationPermission.deniedForever)return; final x=await Geolocator.getCurrentPosition(); final ll=LatLng(x.latitude,x.longitude); setState(()=>origin=ll); map.move(ll,15);});}
  Future<void> routeCalc() async {if(origin==null||destination==null)return; setState(()=>loading=true); try{final u=Uri.parse('https://router.project-osrm.org/route/v1/driving/${origin!.longitude},${origin!.latitude};${destination!.longitude},${destination!.latitude}?overview=full&geometries=geojson'); final r=await http.get(u); final j=jsonDecode(r.body); final coords=j['routes'][0]['geometry']['coordinates'] as List; final pts=coords.map<LatLng>((x)=>LatLng((x[1] as num).toDouble(),(x[0] as num).toDouble())).toList(); setState((){route=pts;km=(j['routes'][0]['distance'] as num).toDouble()/1000;});}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Não foi possível calcular a rota. Verifique a internet.')));}finally{setState(()=>loading=false);}}
  void tapMap(TapPosition _,LatLng p){if(origin==null)setState(()=>origin=p);else if(destination==null){setState(()=>destination=p);routeCalc();}else{setState(()=>destination=p);routeCalc();}}
  @override Widget build(BuildContext context){return Scaffold(body:SafeArea(child:IndexedStack(index:tab,children:[_main(),_settings(),_history()])),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const [NavigationDestination(icon:Icon(Icons.calculate_outlined),selectedIcon:Icon(Icons.calculate),label:'Corrida'),NavigationDestination(icon:Icon(Icons.tune),label:'Configurações'),NavigationDestination(icon:Icon(Icons.history),label:'Histórico')]));}
  Widget _main()=>Column(children:[Padding(padding:const EdgeInsets.fromLTRB(18,14,18,8),child:Row(children:[const Expanded(child:Text('Tarifa Fácil',style:TextStyle(fontSize:25,fontWeight:FontWeight.w800))),IconButton(onPressed:current,icon:const Icon(Icons.my_location)),IconButton(onPressed:()=>setState((){origin=null;destination=null;route=[];km=0;}),icon:const Icon(Icons.refresh))])),Expanded(child:ClipRRect(borderRadius:const BorderRadius.vertical(top:Radius.circular(24)),child:FlutterMap(mapController:map,options:MapOptions(initialCenter:const LatLng(-18.0,-41.0),initialZoom:13,onTap:tapMap),children:[TileLayer(urlTemplate:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',userAgentPackageName:'com.tarifafacil.app'),if(route.isNotEmpty)PolylineLayer(polylines:[Polyline(points:route,strokeWidth:5,color:Colors.green)]),MarkerLayer(markers:[if(origin!=null)Marker(point:origin!,width:42,height:42,child:const Icon(Icons.location_on,color:Colors.green,size:40)),if(destination!=null)Marker(point:destination!,width:42,height:42,child:const Icon(Icons.flag,color:Colors.red,size:38))])]))),Container(padding:const EdgeInsets.fromLTRB(18,14,18,18),decoration:BoxDecoration(color:Theme.of(context).colorScheme.surface,boxShadow:[BoxShadow(blurRadius:12,color:Colors.black.withOpacity(.12))]),child:Column(children:[Row(children:[_metric('Distância', '${km.toStringAsFixed(2)} km'),_metric('R$/km','R$ ${c.perKm.toStringAsFixed(2)}'),_metric('Dinâmica','${c.dynamic.toStringAsFixed(2)}x')]),const SizedBox(height:10),Text('VALOR DA CORRIDA',style:TextStyle(fontSize:12,fontWeight:FontWeight.w700)),Text('R$ ${fare.toStringAsFixed(2)}',style:const TextStyle(fontSize:40,fontWeight:FontWeight.w900)),const SizedBox(height:8),FilledButton.icon(onPressed:loading?null:()=>widget.onHistory(km,fare),icon:const Icon(Icons.check),label:const Text('FINALIZAR CORRIDA'),style:FilledButton.styleFrom(minimumSize:const Size.fromHeight(48)))]));
  Widget _metric(String a,String b)=>Expanded(child:Column(children:[Text(a,style:const TextStyle(fontSize:12)),Text(b,style:const TextStyle(fontWeight:FontWeight.bold))]));
  Widget _settings()=>ListView(padding:const EdgeInsets.all(20),children:[const Text('Configurações',style:TextStyle(fontSize:28,fontWeight:FontWeight.w800)),const SizedBox(height:18),_field('Tarifa base',c.base,(v)=>setState(()=>c.base=v)),_field('Preço por km',c.perKm,(v)=>setState(()=>c.perKm=v)),_field('Tarifa mínima',c.minFare,(v)=>setState(()=>c.minFare=v)),const SizedBox(height:8),Text('Tarifa dinâmica: ${c.dynamic.toStringAsFixed(2)}x',style:const TextStyle(fontWeight:FontWeight.bold)),Slider(value:c.dynamic,min:1,max:3,divisions:20,label:'${c.dynamic.toStringAsFixed(2)}x',onChanged:(v)=>setState(()=>c.dynamic=v)),Wrap(spacing:8,children:[for(final v in [1.0,1.25,1.5,2.0,2.5,3.0])ChoiceChip(label:Text('${v}x'),selected:c.dynamic==v,onSelected:(_)=>setState(()=>c.dynamic=v))]),const SizedBox(height:20),FilledButton.icon(onPressed:()=>widget.onSave(c),icon:const Icon(Icons.save),label:const Text('Salvar configurações'))]);
  Widget _field(String label,double value,ValueChanged<double> on){final ctrl=TextEditingController(text:value.toStringAsFixed(2));return Padding(padding:const EdgeInsets.only(bottom:12),child:TextField(controller:ctrl,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:InputDecoration(labelText:label,prefixText:'R$ ',border:const OutlineInputBorder()),onSubmitted:(x){final v=double.tryParse(x.replaceAll(',','.'));if(v!=null)on(v);}));}
  Widget _history()=>ListView(padding:const EdgeInsets.all(20),children:[const Text('Histórico',style:TextStyle(fontSize:28,fontWeight:FontWeight.w800)),const SizedBox(height:12),if(widget.history.isEmpty)const Center(child:Padding(padding:EdgeInsets.all(30),child:Text('Nenhuma corrida finalizada.'))) else ...widget.history.map((h){final d=DateTime.parse(h['date']);return Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.motorcycle)),title:Text('R$ ${(h['fare'] as num).toStringAsFixed(2)}',style:const TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('${(h['km'] as num).toStringAsFixed(2)} km • ${DateFormat('dd/MM HH:mm').format(d)}'),trailing:Text('R$/km ${(h['km'] as num)>0?((h['fare'] as num)/(h['km'] as num)).toStringAsFixed(2):'—'}'))).toList()]);
}
